apiVersion: v1
kind: Namespace
metadata:
  name: kind-test
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kind-test
  name: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: docker.io/tomcat:9-jre17
---
kind: Service
apiVersion: v1
metadata:
  namespace: kind-test
  name: tomcat
spec:
  selector:
    app: tomcat
  ports:
  - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kind-test
  name: tomcat
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: /tomcat
        backend:
          service:
            name: tomcat
            port:
              number: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kind-test
  name: http-https-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-https-echo
  template:
    metadata:
      labels:
        app: http-https-echo
    spec:
      containers:
      - name: http-https-echo
        image: mendhak/http-https-echo:28
---
kind: Service
apiVersion: v1
metadata:
  namespace: kind-test
  name: http-https-echo
spec:
  selector:
    app: http-https-echo
  ports:
  - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kind-test
  name: http-https-echo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: /echo
        backend:
          service:
            name: http-https-echo
            port:
              number: 8080
